[build-system]
requires = ["setuptools>=69.0.3", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "hypertension-prediction-api"
version = "1.0.0"
description = "FastAPI application for hypertension prediction"
requires-python = ">=3.11" 